PracaMagisterska/Models/LogowanieViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PracaMagisterska.Models
{
    public class LogowanieViewModel
    {
        [Required(ErrorMessage = "Pole wymagane")]
        [StringLength(20, MinimumLength = 4, ErrorMessage = "Niepoprawna ilość znaków")]
        public string Login { get; set; }

        [Required(ErrorMessage = "Pole wymagane")]
        [StringLength(20, MinimumLength = 4, ErrorMessage = "Niepoprawna ilość znaków")]
        [Display(Name ="Hasło")]
        public string Haslo { get; set; }

        [Display(Name ="Zapamiętaj mnie")]
        public bool ZapamietajMnie { get; set; }

    }
}

PracaMagisterska/Models/RejestracjaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PracaMagisterska.Models
{
    public class RejestracjaViewModel
    {
        [Required(ErrorMessage = "Pole wymagane")]
        [StringLength(20, MinimumLength = 4, ErrorMessage = "Niepoprawna ilość znaków")]
        public string Login { get; set; }

        [Display(Name = "Hasło")]
        [Required(ErrorMessage = "Pole wymagane")]
        [StringLength(20, MinimumLength = 4, ErrorMessage = "Niepoprawna ilość znaków")]
        public string Haslo { get; set; }

        [Compare("Haslo", ErrorMessage = "Niezgodne hasła")]
        [Display(Name = "Powtórz hasło")]
        [Required(ErrorMessage = "Pole wymagane")]
        public string PowtorzoneHaslo { get; set; }
    }
}

PracaMagisterska/Controllers/UzytkownikController.cs
using PracaMagisterska.BazaDanych;
using PracaMagisterska.Enums;
using PracaMagisterska.Models;
using PracaMagisterska.Repozytoria;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using PracaMagisterska.Helpers;

namespace PracaMagisterska.Controllers
{
    public class UzytkownikController : Controller
    {


        // GET: Uzytkownik
        public ActionResult Index()
        {
            return View();
        }

        //[HttpGet]
        //[Authorize(Roles = "Administrator")]
        //public ActionResult Anuluj()
        //{
        //    try
        //    {
        //        return RedirectToAction("Index", "Home");
        //    }
        //    catch (Exception ex)
        //    {
        //        return View("Error");
        //    }

        //}

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edytuj()
        {
            try
            {
                return View();
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edytuj(EdytujUzytkownikaViewModel model)
        {
            try
            {
                if (ModelState.IsValid == true)
                {
                    UzytkownikRepozytorium uzytkownikRepozytorium = new UzytkownikRepozytorium();
                    Uzytkownik uzytkownik = uzytkownikRepozytorium.Pobierz(((Uzytkownik)Session["uzytkownik"]).Id);
                    string sol = Guid.NewGuid().ToString();
                    uzytkownik.Sol = sol;
                    uzytkownik.Haslo = MD5Helper.GenerujMD5(model.Haslo + sol);
                    long? rezultatEdycji = uzytkownikRepozytorium.Zapisz(uzytkownik);
                    if (rezultatEdycji != null)
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        return View("Error");
                    }
                }
                else
                {
                    return View("Edytuj", model);
                }
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }

        [HttpGet]
        public ActionResult Zaloguj()
        {
            try
            {
                UzytkownikRepozytorium uzytkownikRepozytorium = new UzytkownikRepozytorium();
                return View("Logowanie");
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }

        [HttpPost]
        public ActionResult Zaloguj(LogowanieViewModel model)
        {
            try
            {
                if (ModelState.IsValid == true)
                {
                    var result = new ApplicationSignInManager(HttpContext.GetOwinContext()).PasswordSignIn(model);

                    switch (result)
                    {
                        case SignInStatus.Success:
                            return RedirectToAction("Index", "Home");

                        case SignInStatus.LockedOut:
                        case SignInStatus.RequiresVerification:
                        case SignInStatus.Failure:
                        default:
                            ModelState.AddModelError("Haslo", "Niepoprawny login lub hasło");
                            return View("Logowanie", model);
                    }

                }
                else
                {
                    return View("Logowanie", model);
                }
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }

        }
        [HttpGet]
        public ActionResult Rejestracja()
        {
            return View("Rejestracja");
        }

        [HttpPost]
        public ActionResult Rejestracja(RejestracjaViewModel model)
        {
            try
            {
                if (ModelState.IsValid == true)
                {
                    UzytkownikRepozytorium uzytkownikRepozytorium = new UzytkownikRepozytorium();
                    Uzytkownik pobranyUzytkownik = uzytkownikRepozytorium.Pobierz(model.Login);
                    if (pobranyUzytkownik == null)
                    {
                        string sol = Guid.NewGuid().ToString(); //robie sol jako GUID i zamieniam na string

                        Uzytkownik uzytkownik = new Uzytkownik()
                        {
                            Sol = sol,
                            Login = model.Login,
                            Haslo = MD5Helper.GenerujMD5(model.Haslo + sol), //generujemy md5 z polaczenia hasla i soli (losowego ciagu znakow) wywoluje metode statyczna z klasy
                                                                             //MD5Helper
                            Rola = (byte)RolaUzytkownika.Administrator
                        };
                        long? rezultatZapisu = uzytkownikRepozytorium.Zapisz(uzytkownik);
                        if (rezultatZapisu != null)
                        {
                            return RedirectToAction("ListaGier", "Gra");
                        }
                        else
                        {
                            return View("Error");
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("Login", "Login jest już zajęty");
                        return View("Rejestracja", model);
                    }
                }
                else
                {
                    return View("Rejestracja", model);
                }
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }

        }
        [HttpPost]
        public ActionResult Wyloguj()
        {
            try
            {
                if (ModelState.IsValid == true)
                {
                    if (Request.IsAuthenticated == true)
                    {
                        Session.Abandon();
                        HttpContext.GetOwinContext().Authentication.SignOut();
                    }
                    return RedirectToAction("Zaloguj");
                }
                else
                {
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }
    }
}

PracaMagisterska/Views/Uzytkownik/Edytuj.cshtml
@using PracaMagisterska.BazaDanych
@using PracaMagisterska.Models
@model EdytujUzytkownikaViewModel


<h2>Edytuj - @User.Identity.Name</h2>


@using (Html.BeginForm("EdytujGracza", "Uzytkownik", FormMethod.Post))
{
    <div class="row">
        <div class="col-sm-5 col-md-3">
            <div class="form-group">
                @Html.LabelFor(x => x.Haslo)
                <div class="input-group">
                    <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                    @Html.PasswordFor(x => x.Haslo, new
               {
                   @class = "form-control",
                   placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(x => x.Haslo).ToHtmlString())
               })
                </div>
                @Html.ValidationMessageFor(x => x.Haslo)
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-5 col-md-3">
            <div class="form-group ">
                @Html.LabelFor(x => x.PowtorzoneHaslo)
                <div class="input-group">
                    <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                    @Html.PasswordFor(x => x.PowtorzoneHaslo, new
               {
                   @class = "form-control",
                   placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(x => x.PowtorzoneHaslo).ToHtmlString())
               })
                </div>
                @Html.ValidationMessageFor(x => x.PowtorzoneHaslo)
            </div>
        </div>
    </div>
    <button class="btn btn-default">Zapisz</button>
    @Html.ActionLink("Anuluj", "Index", "Home", null, new { @class = "btn btn-default" })
}

PracaMagisterska/Views/Uzytkownik/Logowanie.cshtml
@using PracaMagisterska.Models
@model LogowanieViewModel

<h2>Logowanie</h2>

@using (Html.BeginForm("Zaloguj", "Uzytkownik", FormMethod.Post))
{
    <div class="row">
        @*klasa do wierszy (dane elementy sa w nowej lini )*@
        <div class="col-sm-5 col-md-3">
            @*klasa col w zaleznosci czy sm czy md (sugeruje wielkosc wyswietlacza uzytkownika) dostosowuje aplikacje do wielkosci*@
            <div class="form-group">
                @*@Html.Label("Login")*@  @*wyswietle tekstu login w tagu label*@
                @Html.LabelFor(x => x.Login) @*to jest to samo co label zwykly tylko ze pobiera nazwe pola z modelu*@
                <div class="input-group">
                    @*ta klasa daje szare pole w text box*@
                    <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div> @*ten span sluzy do dodana ikonki  a div to jest moje szare pole w tex box*@
                    @Html.TextBoxFor(x => x.Login, new { @class = "form-control", placeholder = Html.DisplayNameFor(x => x.Login) }) @*placeholder
                                                                                              sluzy do pobrania nazwy pola do tex box*@
                </div>
                @Html.ValidationMessageFor(x => x.Login)  @*bez tego nie pojawi sie komunikat ktory napisalismy w viewModel nad polem*@
            </div>

        </div>
    </div>

    <div class="row">
        <div class="col-sm-5 col-md-3">
            <div class="form-group">
                @Html.LabelFor(x => x.Haslo)
                <div class="input-group">
                    <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                    @Html.PasswordFor(x => x.Haslo, new
                   {
                       @class = "form-control",
                       placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(x => x.Haslo).ToHtmlString())
                   })
                </div>
                @Html.ValidationMessageFor(x => x.Haslo)
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-5 col-md-3">
            @Html.CheckBoxFor(x => x.ZapamietajMnie)
            @Html.LabelFor(x=>x.ZapamietajMnie)
        </div>
    </div>
        <button class="btn btn-default">Zaloguj</button>
}

PracaMagisterska/Views/Uzytkownik/Rejestracja.cshtml
@using PracaMagisterska.Models
@model RejestracjaViewModel
@*sluzy do korzystania z pol w modelu i do zdefiniowania typu widoku*@

<h2>Rejestracja</h2>

@using (Html.BeginForm("Rejestracja", "Uzytkownik", FormMethod.Post))
{
    <div class="row">
        <div class="col-sm-5 col-md-3">
            <div class="form-group">
                @Html.LabelFor(x => x.Login)
                <div class="input-group">
                    <div class="input-group-addon"><span class="glyphicon glyphicon-user"></span></div>
                    @Html.TextBoxFor(x => x.Login, new { @class = "form-control", placeholder = Html.DisplayNameFor(x => x.Login) })
                </div>
                @Html.ValidationMessageFor(x => x.Login)
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-5 col-md-3">
            <div class="form-group ">
                @Html.LabelFor(x => x.Haslo)
                <div class="input-group">
                    <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                    @Html.PasswordFor(x => x.Haslo, new { @class = "form-control", placeholder = Html.DisplayNameFor(x => x.Haslo) })
                </div>
                @Html.ValidationMessageFor(x => x.Haslo)
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-sm-5 col-md-3">
            <div class="form-group ">
                @Html.LabelFor(x => x.PowtorzoneHaslo)
                <div class="input-group">
                    <div class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></div>
                    @Html.PasswordFor(x => x.PowtorzoneHaslo, new
               {
                   @class = "form-control",
                   placeholder = HttpUtility.HtmlDecode(Html.DisplayNameFor(x => x.PowtorzoneHaslo).ToHtmlString())
               })
                </div>
                @Html.ValidationMessageFor(x => x.PowtorzoneHaslo)
            </div>
        </div>
    </div>

    <button class="btn btn-default">Rejestracja</button>





}