PracaMagisterska/Controllers/GraController.cs
using PracaMagisterska.BazaDanych;
using PracaMagisterska.Enums;
using PracaMagisterska.Helpers;
using PracaMagisterska.Models;
using PracaMagisterska.Repozytoria;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PracaMagisterska.Controllers
{
    public class GraController : Controller
    {
        [HttpGet]
        [Authorize]
        public ActionResult Statystyki(DateTime? dataOd, DateTime? dataDo, byte? iloscPuenterow, byte? iloscStrzelcow, PlecGracza? plec,
                                        KategoriaWiekowa? kategoriaWiekowaGraczy, long? klubId)
        {
            try
            {
                if (!dataOd.HasValue)
                {
                    dataOd = DateTime.Today.AddMonths(-6);
                }
                if (!dataDo.HasValue)
                {
                    dataDo = DateTime.Today;
                }
                GraRepozytorium graRepozytorium = new GraRepozytorium();
                List<StatystykiZawodnika> listaStatystykGraczy = graRepozytorium.PobierzStatytstyki(dataOd.Value, dataDo.Value, plec, kategoriaWiekowaGraczy,
                        klubId, ((Uzytkownik)Session["uzytkownik"]).Id);
                StatystykiViewModel statystykiViewModel = new StatystykiViewModel()
                {
                    DataDo = dataDo.Value,
                    DataOd = dataOd.Value,
                    Plec = plec,
                    ListaStatystykZawodnikow = listaStatystykGraczy,
                    KategoriaWiekowaGraczy = kategoriaWiekowaGraczy,
                    KlubId = klubId
                };

                if (iloscPuenterow.HasValue)
                {
                    statystykiViewModel.ListaProponowanychZawodnikow.AddRange(listaStatystykGraczy.Where(x => x.Pozycja == PozycjaGracza.Puenter).Take(iloscPuenterow.Value).ToList());
                }
                if (iloscStrzelcow.HasValue)
                {
                    statystykiViewModel.ListaProponowanychZawodnikow.AddRange(listaStatystykGraczy.Where(x => x.Pozycja == PozycjaGracza.Strzelec).Take(iloscStrzelcow.Value).ToList());
                }
                statystykiViewModel.ListaProponowanychZawodnikow = statystykiViewModel.ListaProponowanychZawodnikow.OrderByDescending(x => x.SredniaOcen).ToList();

                return View(statystykiViewModel);
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }

        [HttpGet]
        [Authorize]
        public ActionResult StatystykiGry(long idGry)
        {
            try
            {
                GraRepozytorium graRepozytorium = new GraRepozytorium();
                Gra pobranaGra = graRepozytorium.Pobierz(idGry);
                long? idPobranejPoprzedniejGry = graRepozytorium.PobierzIdPoprzedniejGry(pobranaGra.Typ, pobranaGra.Data, pobranaGra.UzytkownikId);
                List<StatystykiGracza> pobraneStatystykiGry = graRepozytorium.PobierzListeStatystykGry(idGry);

                StatystykiGryViewModel statystykiGryViewModel = new StatystykiGryViewModel()
                {
                    StatystykiGry = new StatystykiGry()
                    {
                        Data = pobranaGra.Data,
                        TypGry = (TypGry)pobranaGra.Typ,
                        ListaStatystykGracza = pobraneStatystykiGry,
                        Id = pobranaGra.Id
                    }
                };
                if (idPobranejPoprzedniejGry != null)
                {
                    Gra pobranaPoprzedniaGra = graRepozytorium.Pobierz(idPobranejPoprzedniejGry.Value);
                    List<StatystykiGracza> pobraneStatystykiPoprzedniejGry = graRepozytorium.PobierzListeStatystykGry(idPobranejPoprzedniejGry.Value);
                    statystykiGryViewModel.StatystykiPoprzedniejGry = new Models.StatystykiGry()
                    {
                        Data = pobranaPoprzedniaGra.Data,
                        Id = pobranaPoprzedniaGra.Id,
                        ListaStatystykGracza = pobraneStatystykiPoprzedniejGry,
                        TypGry = (TypGry)pobranaPoprzedniaGra.Typ
                    };
                }

                return View(statystykiGryViewModel);
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult Usun(long id)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    GraRepozytorium graRepozytorium = new GraRepozytorium();
                    bool rezultatUsuniecia = graRepozytorium.Usun(id);
                    return RedirectToAction("ListaGier");
                }
                else
                {
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }

        [Authorize]
        [HttpGet]
        public ActionResult ListaGier()
        {
            try
            {
                GraRepozytorium graRepozytorium = new GraRepozytorium();
                List<Gra> listaGier = graRepozytorium.PobierzWszystkie(((Uzytkownik)Session["uzytkownik"]).Id);
                return View(listaGier);
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }

        [Authorize]
        [HttpGet]
        public ActionResult DetaleGry(long? id)
        {
            try
            {
                EdytujGreViewModel model = new EdytujGreViewModel();
                model.Id = id;
                GraRepozytorium graRepozytorium = new GraRepozytorium();
                if (id.HasValue)
                {
                    Gra pobranaGra = graRepozytorium.Pobierz(id.Value);
                    model.Data = pobranaGra.Data;
                    model.Miejsce = pobranaGra.Miejsce;
                    model.TypGry = (TypGry)pobranaGra.Typ;
                    model.KategoriaWiekowa = (KategoriaWiekowa)pobranaGra.KategoriaWiekowaGry;
                    OcenaGraczaRepozytorium ocenaGraczaRepozytorium = new OcenaGraczaRepozytorium();
                    model.IloscZadanWTreningu = ocenaGraczaRepozytorium.ZwrocMaksymalnyNrZadania(pobranaGra.Id);
                    if (model.IloscZadanWTreningu == 0)
                    {
                        model.IloscZadanWTreningu = 1;
                    }
                    model.UzupelnijListeGraczy();
                    model.IloscRund = ocenaGraczaRepozytorium.ZwrocMaksymalnyNrRundy(pobranaGra.Id);
                    if (model.IloscRund == 0)
                    {
                        model.IloscRund = 1;
                    }
                    if (pobranaGra.UczestnicyGry.Any())
                    {
                        model.ListaUczestnikow.Clear();
                    }
                    foreach (UczestnikGry uczestnik in pobranaGra.UczestnicyGry.Where(x => !x.CzyUsuniety))
                    {
                        model.ListaUczestnikow.Add(new UczestnikGryViewModel()
                        {
                            GraczId = uczestnik.GraczId,
                            ImiePrzeciwnika = uczestnik.ImiePrzeciwnika,
                            NazwiskoPrzeciwnika = uczestnik.NazwiskoPrzeciwnika,
                            Id = uczestnik.Id
                        });
                    }
                }
                else
                {
                    model.TypGry = TypGry.Trening;
                }
                return View(model);
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult ZapiszDetaleGry(EdytujGreViewModel model)
        {
            try
            {
                if (model.Id > 0 && model.ListaGraczy != null)
                {
                    foreach (var gracz in model.ListaUczestnikow)
                    {
                        if (string.IsNullOrEmpty(gracz.ImiePrzeciwnika))
                        {
                            gracz.ImiePrzeciwnika = "";
                        }
                        if (string.IsNullOrEmpty(gracz.NazwiskoPrzeciwnika))
                        {
                            gracz.NazwiskoPrzeciwnika = "";
                        }
                    }
                }
                //if (ModelState.IsValid)
                {
                    GraRepozytorium graRepozytorium = new GraRepozytorium();
                    Gra gra = null;
                    if (model.Id.HasValue)
                    {
                        gra = graRepozytorium.Pobierz(model.Id.Value);
                    }
                    else
                    {
                        gra = new Gra();
                        gra.Typ = (byte)model.TypGry;
                        gra.KategoriaWiekowaGry = (byte)model.KategoriaWiekowa;
                    }
                    gra.Miejsce = model.Miejsce;
                    gra.Data = (DateTime)model.Data;
                    gra.UzytkownikId = ((Uzytkownik)Session["uzytkownik"]).Id;
                    long? rezultatZapisu = graRepozytorium.Zapisz(gra);

                    if (model.Id.HasValue)
                    {
                        UczestnikGry uczestnikGry = null;
                        UczestnikGryRepozytorium uczestnikGryRepozytorium = new UczestnikGryRepozytorium();
                        foreach (UczestnikGryViewModel uczestnik in model.ListaUczestnikow)
                        {
                            if (uczestnik.Id.HasValue)

PracaMagisterska/Controllers/GraczController.cs
using PracaMagisterska.BazaDanych;
using PracaMagisterska.Enums;
using PracaMagisterska.Helpers;
using PracaMagisterska.Models;
using PracaMagisterska.Repozytoria;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PracaMagisterska.Controllers
{
    public class GraczController : Controller
    {
        //[Authorize]
        //[HttpGet]
        //public ActionResult DodajGracza()
        //{
        //    try
        //    {
        //        return View("DodajGracza");
        //    }
        //    catch (Exception ex)
        //    {
        //        return View("Error");
        //    }
        //}

        [Authorize]
        [HttpGet]
        public ActionResult ListaGraczy()
        {
            try
            {
                GraczRepozytorium listaGraczyRepozytorium = new GraczRepozytorium();
                List<Gracz> listaGraczy = listaGraczyRepozytorium.PobierzWszystkich(((Uzytkownik)Session["uzytkownik"]).Id);
                return View(listaGraczy);
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult Usun(long id)
        {
            try
            {
                if (ModelState.IsValid == true)
                {
                    GraczRepozytorium graczRepozytorium = new GraczRepozytorium();
                    bool rezultatUsuniecia = graczRepozytorium.Usun(id);
                    return RedirectToAction("ListaGraczy");
                }
                else
                {
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }

        [Authorize]
        [HttpGet]
        public ActionResult DetaleGracza(long? id)
        {
            try
            {
                EdytujGraczaViewModel model = new EdytujGraczaViewModel();
                GraczRepozytorium graczRepozytorium = new GraczRepozytorium();
                if (id.HasValue == true)
                {
                    Gracz pobranyGracz = graczRepozytorium.Pobierz(id.Value);
                    model.Id = pobranyGracz.Id;
                    model.Imie = pobranyGracz.Imie;
                    model.Nazwisko = pobranyGracz.Nazwisko;
                    model.NrLicencji = pobranyGracz.NrLicencji;
                    model.KlubId = pobranyGracz.KlubId;
                    model.Pozycja = (PozycjaGracza)pobranyGracz.Pozycja;
                    model.KategoriaWiekowaGracza = (KategoriaWiekowa)pobranyGracz.KategoriaWiekowa;
                    model.Plec = (PlecGracza)pobranyGracz.Plec;
                }
                return View("DetaleGracza", model);
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult ZapiszDetaleGracza(EdytujGraczaViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                //if (!ModelState.IsValid)
                //if(model.KlubId.HasValue)
                //if (!model.KlubId.HasValue)
                {
                    GraczRepozytorium graczRepozytorium = new GraczRepozytorium();
                    Gracz gracz = null;
                    if (model.Id.HasValue)
                    {
                        gracz = graczRepozytorium.Pobierz(model.Id.Value);
                    }
                    else
                    {
                        gracz = new Gracz();
                    }
                    gracz.Imie = model.Imie;
                    gracz.Nazwisko = model.Nazwisko;
                    gracz.NrLicencji = model.NrLicencji;
                    gracz.Pozycja = (byte)model.Pozycja;
                    gracz.KlubId = model.KlubId;
                    gracz.Plec = (byte)model.Plec;
                    gracz.KategoriaWiekowa = (byte)model.KategoriaWiekowaGracza;
                    gracz.UzytkownikId = ((Uzytkownik)Session["uzytkownik"]).Id;
                    long? rezultatZapisu = graczRepozytorium.Zapisz(gracz);
                    if (rezultatZapisu != null)
                    {
                        return RedirectToAction("ListaGraczy");
                    }
                    else
                    {
                        return View("Error");
                    }
                }
                else
                {
                    return View("DetaleGracza", model);
                }
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }
        //[Authorize]
        //[HttpPost]
        //public ActionResult Zapisz(EdytujGraczaViewModel model)
        //{
        //    try
        //    {
        //        if (ModelState.IsValid == true)
        //        {
        //            GraczRepozytorium graczRepozytorium = new GraczRepozytorium();
        //            Gracz pobranyGracz = graczRepozytorium.Pobierz(model.Imie, model.Nazwisko);
        //            if (pobranyGracz == null)
        //            {
        //                Gracz gracz = new Gracz()
        //                {
        //                    Imie = model.Imie,
        //                    Nazwisko = model.Nazwisko,
        //                    NrLicencji = model.NrLicencji,
        //                    Pozycja = (byte)model.Pozycja
        //                    //Klub=model.ListaKlubow,
        //                };
        //                long? rezultatZapisu = graczRepozytorium.Zapisz(gracz);
        //                if (rezultatZapisu != null)
        //                {
        //                    return RedirectToAction("ListaGraczy", "Gracz");
        //                }
        //                else
        //                {
        //                    return View("Error");
        //                }
        //            }
        //            else
        //            {
        //                return View("DodajGracza", model);
        //            }
        //        }
        //        else
        //        {
        //            return View("DodajGracza", model);
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        return View("Error");
        //    }
        //}
    }
}

PracaMagisterska/Views/Shared/_Layout.cshtml
@using PracaMagisterska.Enums;
@using PracaMagisterska.BazaDanych;
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Praca magisterska</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/js")
    @RenderSection("scripts", required: false)

    <script>
        $.validator.setDefaults({
            highlight: function (element) {
                $(element).closest('.form-group').addClass('has-error');
            },
            unhighlight: function (element) {
                $(element).closest('.form-group').removeClass('has-error');
            },
            errorElement: 'span',
            errorClass: 'help-block',
            errorPlacement: function (error, element) {
                if (element.parent('.input-group').length) {
                    error.insertAfter(element.parent());
                } else {
                    error.insertAfter(element);
                }
            }
        });

        function escapeRegExp(str) {
            return str.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");
        }

        String.prototype.replaceAll = function (search, replacement) {
            var target = this;
            return target.replace(new RegExp(escapeRegExp(search), 'g'), replacement);
        };

        jQuery(function ($) {
            $.validator.addMethod('date',
                function (value, element) {
                    return this.optional(element) || moment(value, 'YYYY-MM-DD HH:mm').isValid() || moment(value, 'YYYY-MM-DD').isValid();
                });
        });

        $(document).ready(function () {
            autosize($('textarea'));
            $('#link-wyloguj').click(function () {
                $('#form-wyloguj').submit();
            });
            $('.input-group.date-time').datetimepicker({
                locale: 'pl'
            });
            $('.input-group.date').datetimepicker({
                locale: 'pl',
                format: 'YYYY-MM-DD'
            });
        });

    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Strona główna", "Index2", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-left">
                    @if (Request.IsAuthenticated == true)
                    {
                        <li>
                            @Html.ActionLink("Lista graczy", "ListaGraczy", "Gracz")
                        </li>
                        <li>
                            @Html.ActionLink("Lista gier", "ListaGier", "Gra")
                        </li>
                        <li>
                            @Html.ActionLink("Najlepsi zawodnicy", "Index", "Home")
                        </li>
                        <li>
                            @Html.ActionLink("Statystyki", "Statystyki", "Gra")
                        </li>
                        <li>
                            @Html.ActionLink("Notatki", "ListaNotatek", "Notatka")
                        </li>
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        @if (Request.IsAuthenticated == false)
                        {
                        <li>@Html.ActionLink("Zaloguj", "Zaloguj", "Uzytkownik")</li>
                        <li>@Html.ActionLink("Zarejestruj", "Rejestracja", "Uzytkownik")</li>
                        }
                        else
                        {
                            <li>
                                <a>@User.Identity.Name</a>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="caret"></span></a>
                                <ul class="dropdown-menu navbar-inverse navbar-nav">
                                    <li>
                                        @Html.ActionLink("Edytuj", "Edytuj", "Uzytkownik")
                                    </li>
                                    <li>
                                        <a id="link-wyloguj" href="#">Wyloguj</a>
                                        @using (Html.BeginForm("Wyloguj", "Uzytkownik", FormMethod.Post, new { id = "form-wyloguj" }))
                                        {

                                        }
                                    </li>
                                </ul>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year — Praca mgr Konrad Kulikowski</p>
                @*@User.Identity.Name
                    @(((PracaMagisterskaEntities.BazaDanych.Uzytkownik)Session["uzytkownik"]).Id)*@
            </footer>
        </div>
    </body>
</html>