PracaMagisterska/Controllers/NotatkaController.cs
using PracaMagisterska.BazaDanych;
using PracaMagisterska.Helpers;
using PracaMagisterska.Models;
using PracaMagisterska.Repozytoria;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PracaMagisterska.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class NotatkaController : Controller
    {

        [HttpGet]
        public ActionResult ListaNotatek()
        {
            try
            {
                NotatkaRepozytorium notatkaRepozytorium = new NotatkaRepozytorium();
                List<Notatka> notatka = notatkaRepozytorium.PobierzWszystkie(((Uzytkownik)Session["uzytkownik"]).Id);
                return View("ListaNotatek", notatka);
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
            finally
            {

            }
        }

        [HttpPost]
        public ActionResult Usun(long id)
        {
            if (ModelState.IsValid == true)
            {
                try
                {
                    NotatkaRepozytorium notatkaRepozytorium = new NotatkaRepozytorium();
                    bool rezultatUsuniecia = notatkaRepozytorium.Usun(id);

                    return RedirectToAction("ListaNotatek");
                }
                catch (Exception ex)
                {
                    return View("Error");
                }
            }
            else
            {
                return View("Error");
            }
        }

        [HttpGet]
        public ActionResult DetaleNotatki(long? id)
        {
            try
            {
                EdytujNotatkeViewModel model = new EdytujNotatkeViewModel();
                NotatkaRepozytorium notatkaRepozytorium = new NotatkaRepozytorium();
                if (id.HasValue == true)
                {
                    Notatka pobranaNotatka = notatkaRepozytorium.Pobierz(id.Value);
                    model.Id = pobranaNotatka.Id;
                    model.DataDodania = pobranaNotatka.DataDodania;
                    model.Temat = pobranaNotatka.Temat;
                    model.Tresc = pobranaNotatka.Tresc;
                }
                return View("DetaleNotatki", model);
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }

        [HttpPost]
        public ActionResult ZapiszDetaleNotatki(EdytujNotatkeViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    NotatkaRepozytorium notatkaRepozytorium = new NotatkaRepozytorium();
                    Notatka notatka = null;
                    if (model.Id.HasValue)
                    {
                        notatka = notatkaRepozytorium.Pobierz(model.Id.Value);
                    }
                    else
                    {
                        notatka = new Notatka();
                    }
                    notatka.Temat = model.Temat;
                    notatka.Tresc = model.Tresc;
                    notatka.UzytkownikId = ((Uzytkownik)Session["uzytkownik"]).Id;
                    notatka.DataDodania = DateTime.Now;
                    long? rezultatZapisu = notatkaRepozytorium.Zapisz(notatka);
                    if (rezultatZapisu != null)
                    {
                        return RedirectToAction("ListaNotatek");
                    }
                    else
                    {
                        return View("Error");
                    }
                }
                else
                {
                    return View("DetaleNotatki", model);
                }
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }
    }
}

PracaMagisterska/Views/Notatka/DetaleNotatki.cshtml
@model EdytujNotatkeViewModel

<h2>Detale notatki</h2>


@using (Html.BeginForm("ZapiszDetaleNotatki", "Notatka", FormMethod.Post))
{
    @Html.HiddenFor(x => x.Id)
    <div class="row">
        <div class="col-sm-12">
            <div class="form-group">
                @Html.LabelFor(x => x.Temat)
                <div class="input-group">
                    <div class="input-group-addon"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></div>
                    @Html.TextBoxFor(x => x.Temat, new { @class = "form-control", placeholder = Html.DisplayNameFor(x => x.Temat) })
                </div>
                @Html.ValidationMessageFor(x => x.Temat)
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="form-group">
                @Html.LabelFor(x => x.Tresc)
                <div class="input-group">
                    <div class="input-group-addon"><span class="glyphicon glyphicon-comment" aria-hidden="true"></span></div>
                    @Html.TextAreaFor(x => x.Tresc, new { @class = "form-control", placeholder = Html.DisplayNameFor(x => x.Tresc) })
                </div>
                @Html.ValidationMessageFor(x => x.Tresc)
            </div>
        </div>
    </div>


    <button class="btn btn-default">Zapisz</button>
    @Html.ActionLink("Anuluj", "ListaNotatek", "Notatka", null, new { @class = "btn btn-default" })
}

PracaMagisterska/Views/Notatka/ListaNotatek.cshtml
@model List<Notatka>

<script>

    $(document).ready(function () {
        $('.btn-usun').click(function () {
            var btn = $(this);

            swal({
                title: 'Na pewno chcesz to usunąć?',
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Tak,chcę to usunąć!',
                cancelButtonText: 'Anuluj'
            }).then(function () {
                $(btn).closest('form').submit();
            })
        });

    });

</script>

<h2>Lista notatek</h2>

@Html.ActionLink("Dodaj notatkę", "DetaleNotatki", null, new { @class = "btn btn-default" })

<div class="row">
    <div class="col-sm-12">
        <table class="table table-striped" style="margin:20px">
            <tr>
                <th class="col-sm-3">
                    Temat
                </th>
                <th class="col-sm-6">
                    Treść
                </th>
                <th class="col-sm-3">
                    Data
                </th>
                <th></th>
                <th></th>
            </tr>
            @if (Model.Count == 0)
            {
                <tr>
                    <td></td>
                    <td class="text-center">
                        Brak danych.
                    </td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            }
            @foreach (Notatka notatka in Model)
            {
                <tr>
                    <td class="col-sm-3">
                        @notatka.Temat
                    </td>
                    <td class="col-sm-6">
                        @notatka.Tresc
                    </td>
                    <td class="col-sm-3">
                        @notatka.DataDodania
                    </td>
                    <td>
                        <a href="@Url.Action("DetaleNotatki", "Notatka", new { id = notatka.Id })" class="btn btn-default btn-sm pull-left" title="Edytuj" style="margin-right:10px;"><span class="glyphicon glyphicon-cog"></span></a>
                    </td>
                    <td>
                        @using (Html.BeginForm("Usun", "Notatka", FormMethod.Post))
                        {
                            @Html.Hidden("id", notatka.Id)  @*nazwa ma byc tak jak nazwa parametru w kontrolerze , a wartosc pobieramy z konkretnego elementu modelu*@
                            <button type="button" title="Usuń" class="btn btn-default btn-sm btn-usun">
                                <span class="glyphicon glyphicon-trash "></span>
                            </button>
                        }
                    </td>

                </tr>
            }
        </table>
    </div>
</div>